### PR TITLE
Update Packer to version 0.10.1

### PR DESCRIPTION
**Pull request by netflash**
* add spec tests to test kitchen
* add centos7 to test kitchen
* update default URL to a working one

### CODE REVIEW

**Comment by netflash** [comment]
Hey, is there any chance this could be merged ?

**Comment by sit** [comment]
I can't really test this stuff any more; do you want to take over maintenance? I'm happy to merge and transfer the thing over to you for publishing/maintenance.

**Comment by netflash** [comment]
Let's do it then. 
Could you please transfer it to https://github.com/strataconsulting/ ?
I gonna maintain this cookbook for a while and update chef supermarket, etc.

**Comment by sit** [comment]
Cool, can you verify your account in supermarket by signing the ICLA or CCLA? Thanks.

**Comment by netflash** [comment]
Thanks for your patience - I've got ICLA. Same username - netflash.

**Comment by sit** [comment]
I've added you as a collaborator here and on chef supermarket. (It looks like I can't transfer it to you.)

Thanks for taking this over!

**Pull request merged**
